// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Dataset
 */
export type Dataset = {
    /**
     * Datasetid
     */
    datasetId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: number;
    /**
     * Lastupdatedby
     */
    lastUpdatedBy: string;
    /**
     * Lastupdatedon
     */
    lastUpdatedOn: string;
    query: DatasetQuery;
    /**
     * Results
     */
    results?: Array<unknown>;
};

/**
 * DatasetFieldEnum
 *
 * An enumeration.
 */
export type DatasetFieldEnum = 'datasetId' | 'name' | 'version' | 'lastUpdatedBy' | 'lastUpdatedOn' | 'query' | 'results';

/**
 * DatasetQuery
 */
export type DatasetQuery = {
    /**
     * Endpoint
     */
    endpoint: string;
    /**
     * Filters
     */
    filters: Array<QueryFilter>;
    /**
     * Node Deduplication Field
     */
    node_deduplication_field?: string;
    /**
     * Node Group Criteria
     */
    node_group_criteria?: Array<string>;
    /**
     * Node Group Layout
     */
    node_group_layout?: string;
};

/**
 * DatasetRevision
 */
export type DatasetRevision = {
    /**
     * Name
     */
    name: string;
    query: DatasetQuery;
};

/**
 * Edge
 */
export type Edge = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Endpoints
     */
    endpoints: Array<Node>;
    /**
     * Source
     */
    source: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Config
     */
    model_config?: {
        [key: string]: unknown;
    };
};

/**
 * EdgeMeta
 */
export type EdgeMeta = {
    /**
     * Capacity
     */
    capacity?: number;
    /**
     * Endpoint Identifiers
     */
    endpoint_identifiers: {
        [key: string]: Array<unknown>;
    };
};

/**
 * GoogleSheet
 */
export type GoogleSheet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InputModifier
 *
 * An enumeration.
 */
export type InputModifier = 'not_like' | 'like' | 'not_equal' | '';

/**
 * LayerConfiguration
 */
export type LayerConfiguration = {
    /**
     * Visible
     */
    visible: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color: string;
    /**
     * Edgewidth
     */
    edgeWidth: number;
    /**
     * Pathoffset
     */
    pathOffset: number;
    /**
     * Nodewidth
     */
    nodeWidth: number;
    /**
     * Jsonfromurl
     */
    jsonFromUrl: boolean;
    /**
     * Mapjson
     */
    mapjson?: string;
    /**
     * Mapjsonurl
     */
    mapjsonUrl?: string;
    /**
     * Endpointid
     */
    endpointId: string;
    /**
     * Inboundvaluefield
     */
    inboundValueField?: string;
    /**
     * Outboundvaluefield
     */
    outboundValueField?: string;
    /**
     * Srcfield
     */
    srcField?: string;
    /**
     * Dstfield
     */
    dstField?: string;
    /**
     * Legend
     */
    legend?: boolean;
    /**
     * Nodehighlight
     */
    nodeHighlight?: string;
};

/**
 * Map
 */
export type _Map = {
    /**
     * Mapid
     */
    mapId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: number;
    /**
     * Overrides
     */
    overrides: {
        [key: string]: MapOverrides;
    };
    configuration: MapConfiguration;
    /**
     * Lastupdatedby
     */
    lastUpdatedBy: string;
    /**
     * Lastupdatedon
     */
    lastUpdatedOn: string;
    /**
     * Public
     */
    public?: boolean;
};

/**
 * MapConfiguration
 */
export type MapConfiguration = {
    /**
     * Initialviewstrategy
     */
    initialViewStrategy: string;
    /**
     * Latitudevar
     */
    latitudeVar?: string;
    /**
     * Longitudevar
     */
    longitudeVar?: string;
    viewport: Viewport;
    /**
     * Background
     */
    background: string;
    tileset: TilesetConfiguration;
    /**
     * Editmode
     */
    editMode: boolean;
    /**
     * Showsidebar
     */
    showSidebar: boolean;
    /**
     * Showviewcontrols
     */
    showViewControls: boolean;
    /**
     * Showlegend
     */
    showLegend: boolean;
    /**
     * Legendcolumnlength
     */
    legendColumnLength?: number;
    /**
     * Legendposition
     */
    legendPosition?: string;
    /**
     * Legenddefaultbehavior
     */
    legendDefaultBehavior?: string;
    /**
     * Enablescrolling
     */
    enableScrolling: boolean;
    /**
     * Enableediting
     */
    enableEditing: boolean;
    /**
     * Enablenodeanimation
     */
    enableNodeAnimation: boolean;
    /**
     * Enableedgeanimation
     */
    enableEdgeAnimation: boolean;
    /**
     * Thresholds
     */
    thresholds?: Array<unknown>;
    /**
     * Zindexbase
     */
    zIndexBase: number;
    /**
     * Layers
     */
    layers: Array<LayerConfiguration>;
};

/**
 * MapFieldEnum
 *
 * An enumeration.
 */
export type MapFieldEnum = 'mapId' | 'name' | 'version' | 'overrides' | 'configuration' | 'lastUpdatedBy' | 'lastUpdatedOn' | 'public';

/**
 * MapOverrides
 */
export type MapOverrides = {
    /**
     * Nodes
     */
    nodes: {
        [key: string]: OverrideRule;
    };
    /**
     * Edges
     */
    edges: {
        [key: string]: OverrideRule;
    };
};

/**
 * MapRevision
 */
export type MapRevision = {
    /**
     * Name
     */
    name: string;
    /**
     * Overrides
     */
    overrides: {
        [key: string]: MapOverrides;
    };
    configuration: MapConfiguration;
};

/**
 * NamedDatasource
 */
export type NamedDatasource = {
    [key: string]: unknown;
};

/**
 * NewTemplate
 */
export type NewTemplate = {
    /**
     * Name
     */
    name: string;
    /**
     * Template
     */
    template: string;
};

/**
 * Node
 */
export type Node = {
    /**
     * Name
     */
    name: string;
    /**
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     */
    longitude: number;
    /**
     * Description
     */
    description?: string;
    /**
     * Model Config
     */
    model_config?: {
        [key: string]: unknown;
    };
};

/**
 * OverrideRule
 */
export type OverrideRule = {
    operation: OverrideType;
    /**
     * State
     */
    state?: {
        [key: string]: unknown;
    };
    /**
     * Render
     */
    render?: boolean;
};

/**
 * OverrideType
 *
 * An enumeration.
 */
export type OverrideType = 'delete' | 'add' | 'override';

/**
 * PasswordReset
 */
export type PasswordReset = {
    /**
     * Password
     */
    password: string;
};

/**
 * QueryFilter
 */
export type QueryFilter = {
    /**
     * Field
     */
    field: string;
    operator?: InputModifier;
    /**
     * Value
     */
    value: Array<string>;
    /**
     * Templated
     */
    templated?: boolean;
};

/**
 * ScopeEnum
 *
 * An enumeration.
 */
export type ScopeEnum = 'terranova:maps:read' | 'terranova:maps:write' | 'terranova:maps:publish' | 'terranova:admin';

/**
 * Template
 */
export type Template = {
    /**
     * Templateid
     */
    templateId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: number;
    /**
     * Lastupdatedby
     */
    lastUpdatedBy: string;
    /**
     * Lastupdatedon
     */
    lastUpdatedOn: string;
    /**
     * Template
     */
    template: string;
};

/**
 * TemplateFieldEnum
 *
 * An enumeration.
 */
export type TemplateFieldEnum = 'templateId' | 'name' | 'version' | 'lastUpdatedBy' | 'lastUpdatedOn' | 'template';

/**
 * TerranovaDatatype
 *
 * An enumeration.
 */
export type TerranovaDatatype = 'live' | 'snapshot';

/**
 * TerranovaLayout
 *
 * An enumeration.
 */
export type TerranovaLayout = 'geographic' | 'logical';

/**
 * TerranovaOutputType
 *
 * An enumeration.
 */
export type TerranovaOutputType = 'json' | 'svg';

/**
 * TilesetConfiguration
 */
export type TilesetConfiguration = {
    /**
     * Geographic
     */
    geographic?: string;
    /**
     * Boundaries
     */
    boundaries?: string;
    /**
     * Labels
     */
    labels?: string;
};

/**
 * Topology
 */
export type Topology = {
    /**
     * Nodes
     */
    nodes: Array<TopologyNodes>;
    /**
     * Edges
     */
    edges: Array<TopologyEdges>;
    /**
     * Layer
     */
    layer?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Pathlayout
     */
    pathLayout: {
        [key: string]: unknown;
    };
};

/**
 * TopologyEdges
 */
export type TopologyEdges = {
    /**
     * Name
     */
    name: string;
    /**
     * Coordinates
     */
    coordinates: Array<[
        number,
        number
    ]>;
    meta: EdgeMeta;
};

/**
 * TopologyNodes
 */
export type TopologyNodes = {
    /**
     * Name
     */
    name: string;
    /**
     * Coordinate
     */
    coordinate: [
        number,
        number
    ];
    /**
     * Meta
     */
    meta: {
        [key: string]: unknown;
    };
    /**
     * Children
     */
    children?: Array<string>;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    scope: Array<ScopeEnum>;
    /**
     * Password
     */
    password: string;
};

/**
 * UserData
 */
export type UserData = {
    /**
     * Favorites
     */
    favorites: {
        [key: string]: Array<string>;
    };
    /**
     * Lastedited
     */
    lastEdited: {
        [key: string]: Array<string>;
    };
    /**
     * Username
     */
    username: string;
};

/**
 * UserDataRevision
 */
export type UserDataRevision = {
    /**
     * Favorites
     */
    favorites: {
        [key: string]: Array<string>;
    };
    /**
     * Lastedited
     */
    lastEdited: {
        [key: string]: Array<string>;
    };
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    scope: Array<ScopeEnum>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VersionEnum
 *
 * An enumeration.
 */
export type VersionEnum = 'all' | 'latest';

/**
 * Viewport
 */
export type Viewport = {
    center?: ViewportCenter;
    /**
     * Top
     */
    top?: number;
    /**
     * Left
     */
    left?: number;
    /**
     * Bottom
     */
    bottom?: number;
    /**
     * Right
     */
    right?: number;
    /**
     * Zoom
     */
    zoom?: number;
};

/**
 * ViewportCenter
 */
export type ViewportCenter = {
    /**
     * Lat
     */
    lat: number;
    /**
     * Lng
     */
    lng: number;
};

export type MapByIdMapIdMapIdGetData = {
    body?: never;
    path: {
        /**
         * Mapid
         */
        mapId: string;
    };
    query?: never;
    url: '/map/id/{mapId}/';
};

export type MapByIdMapIdMapIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MapByIdMapIdMapIdGetError = MapByIdMapIdMapIdGetErrors[keyof MapByIdMapIdMapIdGetErrors];

export type MapByIdMapIdMapIdGetResponses = {
    /**
     * Successful Response
     */
    200: _Map;
};

export type MapByIdMapIdMapIdGetResponse = MapByIdMapIdMapIdGetResponses[keyof MapByIdMapIdMapIdGetResponses];

export type UpdateMapMapIdMapIdPutData = {
    body: MapRevision;
    path: {
        /**
         * Mapid
         */
        mapId: string;
    };
    query?: never;
    url: '/map/id/{mapId}/';
};

export type UpdateMapMapIdMapIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMapMapIdMapIdPutError = UpdateMapMapIdMapIdPutErrors[keyof UpdateMapMapIdMapIdPutErrors];

export type UpdateMapMapIdMapIdPutResponses = {
    /**
     * Response Update Map Map Id  Mapid   Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateMapMapIdMapIdPutResponse = UpdateMapMapIdMapIdPutResponses[keyof UpdateMapMapIdMapIdPutResponses];

export type MapsMapsGetData = {
    body?: never;
    path?: never;
    query?: {
        fields?: Array<MapFieldEnum>;
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | string;
        /**
         * Mapid
         */
        mapId?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Lastupdatedby
         */
        lastUpdatedBy?: Array<string>;
        /**
         * Public
         */
        public?: boolean;
    };
    url: '/maps/';
};

export type MapsMapsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MapsMapsGetError = MapsMapsGetErrors[keyof MapsMapsGetErrors];

export type MapsMapsGetResponses = {
    /**
     * Response Maps Maps  Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type MapsMapsGetResponse = MapsMapsGetResponses[keyof MapsMapsGetResponses];

export type CreateMapMapPostData = {
    body: MapRevision;
    path?: never;
    query?: never;
    url: '/map/';
};

export type CreateMapMapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMapMapPostError = CreateMapMapPostErrors[keyof CreateMapMapPostErrors];

export type CreateMapMapPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PublishMapMapIdMapIdPublishPostData = {
    body?: never;
    path: {
        /**
         * Mapid
         */
        mapId: string;
    };
    query?: never;
    url: '/map/id/{mapId}/publish/';
};

export type PublishMapMapIdMapIdPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishMapMapIdMapIdPublishPostError = PublishMapMapIdMapIdPublishPostErrors[keyof PublishMapMapIdMapIdPublishPostErrors];

export type PublishMapMapIdMapIdPublishPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PublicMapsPublicMapsGetData = {
    body?: never;
    path?: never;
    query?: {
        fields?: Array<MapFieldEnum>;
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | string;
        /**
         * Mapid
         */
        mapId?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Lastupdatedby
         */
        lastUpdatedBy?: Array<string>;
    };
    url: '/public/maps/';
};

export type PublicMapsPublicMapsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicMapsPublicMapsGetError = PublicMapsPublicMapsGetErrors[keyof PublicMapsPublicMapsGetErrors];

export type PublicMapsPublicMapsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DsMetadataDatasourcesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/';
};

export type DsMetadataDatasourcesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DatasetsDatasetsGetData = {
    body?: never;
    path?: never;
    query?: {
        fields?: Array<DatasetFieldEnum>;
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | number;
        /**
         * Datasetid
         */
        datasetId?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Lastupdatedby
         */
        lastUpdatedBy?: Array<string>;
    };
    url: '/datasets/';
};

export type DatasetsDatasetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DatasetsDatasetsGetError = DatasetsDatasetsGetErrors[keyof DatasetsDatasetsGetErrors];

export type DatasetsDatasetsGetResponses = {
    /**
     * Response Datasets Datasets  Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type DatasetsDatasetsGetResponse = DatasetsDatasetsGetResponses[keyof DatasetsDatasetsGetResponses];

export type DatasetByIdDatasetIdDatasetIdGetData = {
    body?: never;
    path: {
        /**
         * Datasetid
         */
        datasetId: string;
    };
    query?: never;
    url: '/dataset/id/{datasetId}/';
};

export type DatasetByIdDatasetIdDatasetIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DatasetByIdDatasetIdDatasetIdGetError = DatasetByIdDatasetIdDatasetIdGetErrors[keyof DatasetByIdDatasetIdDatasetIdGetErrors];

export type DatasetByIdDatasetIdDatasetIdGetResponses = {
    /**
     * Successful Response
     */
    200: Dataset;
};

export type DatasetByIdDatasetIdDatasetIdGetResponse = DatasetByIdDatasetIdDatasetIdGetResponses[keyof DatasetByIdDatasetIdDatasetIdGetResponses];

export type UpdateDatasetDatasetIdDatasetIdPutData = {
    body: DatasetRevision;
    path: {
        /**
         * Datasetid
         */
        datasetId: string;
    };
    query?: never;
    url: '/dataset/id/{datasetId}/';
};

export type UpdateDatasetDatasetIdDatasetIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDatasetDatasetIdDatasetIdPutError = UpdateDatasetDatasetIdDatasetIdPutErrors[keyof UpdateDatasetDatasetIdDatasetIdPutErrors];

export type UpdateDatasetDatasetIdDatasetIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateDatasetDatasetPostData = {
    body: DatasetRevision;
    path?: never;
    query?: never;
    url: '/dataset/';
};

export type CreateDatasetDatasetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDatasetDatasetPostError = CreateDatasetDatasetPostErrors[keyof CreateDatasetDatasetPostErrors];

export type CreateDatasetDatasetPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TemplateByIdTemplateIdTemplateIdGetData = {
    body?: never;
    path: {
        /**
         * Templateid
         */
        templateId: string;
    };
    query?: never;
    url: '/template/id/{templateId}/';
};

export type TemplateByIdTemplateIdTemplateIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TemplateByIdTemplateIdTemplateIdGetError = TemplateByIdTemplateIdTemplateIdGetErrors[keyof TemplateByIdTemplateIdTemplateIdGetErrors];

export type TemplateByIdTemplateIdTemplateIdGetResponses = {
    /**
     * Successful Response
     */
    200: Template;
};

export type TemplateByIdTemplateIdTemplateIdGetResponse = TemplateByIdTemplateIdTemplateIdGetResponses[keyof TemplateByIdTemplateIdTemplateIdGetResponses];

export type UpdateTemplateTemplateIdTemplateIdPutData = {
    body: NewTemplate;
    path: {
        /**
         * Templateid
         */
        templateId: string;
    };
    query?: never;
    url: '/template/id/{templateId}/';
};

export type UpdateTemplateTemplateIdTemplateIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTemplateTemplateIdTemplateIdPutError = UpdateTemplateTemplateIdTemplateIdPutErrors[keyof UpdateTemplateTemplateIdTemplateIdPutErrors];

export type UpdateTemplateTemplateIdTemplateIdPutResponses = {
    /**
     * Response Update Template Template Id  Templateid   Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateTemplateTemplateIdTemplateIdPutResponse = UpdateTemplateTemplateIdTemplateIdPutResponses[keyof UpdateTemplateTemplateIdTemplateIdPutResponses];

export type TemplatesTemplatesGetData = {
    body?: never;
    path?: never;
    query?: {
        fields?: Array<TemplateFieldEnum>;
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | string;
        /**
         * Templateid
         */
        templateId?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Lastupdatedby
         */
        lastUpdatedBy?: Array<string>;
    };
    url: '/templates/';
};

export type TemplatesTemplatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TemplatesTemplatesGetError = TemplatesTemplatesGetErrors[keyof TemplatesTemplatesGetErrors];

export type TemplatesTemplatesGetResponses = {
    /**
     * Response Templates Templates  Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type TemplatesTemplatesGetResponse = TemplatesTemplatesGetResponses[keyof TemplatesTemplatesGetResponses];

export type CreateTemplateTemplatePostData = {
    body: NewTemplate;
    path?: never;
    query?: never;
    url: '/template/';
};

export type CreateTemplateTemplatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTemplateTemplatePostError = CreateTemplateTemplatePostErrors[keyof CreateTemplateTemplatePostErrors];

export type CreateTemplateTemplatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DatasetOutputOutputDatasetDatasetIdLayoutDatatypeOutputTypeGetData = {
    body?: never;
    path: {
        /**
         * Dataset Id
         */
        dataset_id: string;
        layout: TerranovaLayout;
        datatype: TerranovaDatatype;
        output_type: TerranovaOutputType;
    };
    query?: {
        /**
         * Template
         */
        template?: string;
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | number;
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/output/dataset/{dataset_id}/{layout}/{datatype}/{output_type}/';
};

export type DatasetOutputOutputDatasetDatasetIdLayoutDatatypeOutputTypeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DatasetOutputOutputDatasetDatasetIdLayoutDatatypeOutputTypeGetError = DatasetOutputOutputDatasetDatasetIdLayoutDatatypeOutputTypeGetErrors[keyof DatasetOutputOutputDatasetDatasetIdLayoutDatatypeOutputTypeGetErrors];

export type DatasetOutputOutputDatasetDatasetIdLayoutDatatypeOutputTypeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OutputDatasetRevisionRawOutputQueryRawPatchData = {
    body: DatasetRevision;
    path?: never;
    query?: {
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/output/query/raw/';
};

export type OutputDatasetRevisionRawOutputQueryRawPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutputDatasetRevisionRawOutputQueryRawPatchError = OutputDatasetRevisionRawOutputQueryRawPatchErrors[keyof OutputDatasetRevisionRawOutputQueryRawPatchErrors];

export type OutputDatasetRevisionRawOutputQueryRawPatchResponses = {
    /**
     * Response Output Dataset Revision Raw Output Query Raw  Patch
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type OutputDatasetRevisionRawOutputQueryRawPatchResponse = OutputDatasetRevisionRawOutputQueryRawPatchResponses[keyof OutputDatasetRevisionRawOutputQueryRawPatchResponses];

export type OutputDatasetQueryOutputQueryLayoutGetData = {
    body: NamedDatasource;
    path: {
        layout: TerranovaLayout;
    };
    query?: {
        /**
         * Template
         */
        template?: string;
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/output/query/{layout}/';
};

export type OutputDatasetQueryOutputQueryLayoutGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutputDatasetQueryOutputQueryLayoutGetError = OutputDatasetQueryOutputQueryLayoutGetErrors[keyof OutputDatasetQueryOutputQueryLayoutGetErrors];

export type OutputDatasetQueryOutputQueryLayoutGetResponses = {
    /**
     * Successful Response
     */
    200: Topology;
};

export type OutputDatasetQueryOutputQueryLayoutGetResponse = OutputDatasetQueryOutputQueryLayoutGetResponses[keyof OutputDatasetQueryOutputQueryLayoutGetResponses];

export type OutputDatasetRevisionOutputQueryLayoutPatchData = {
    body: DatasetRevision;
    path: {
        layout: TerranovaLayout;
    };
    query?: {
        /**
         * Template
         */
        template?: string;
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/output/query/{layout}/';
};

export type OutputDatasetRevisionOutputQueryLayoutPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutputDatasetRevisionOutputQueryLayoutPatchError = OutputDatasetRevisionOutputQueryLayoutPatchErrors[keyof OutputDatasetRevisionOutputQueryLayoutPatchErrors];

export type OutputDatasetRevisionOutputQueryLayoutPatchResponses = {
    /**
     * Successful Response
     */
    200: Topology;
};

export type OutputDatasetRevisionOutputQueryLayoutPatchResponse = OutputDatasetRevisionOutputQueryLayoutPatchResponses[keyof OutputDatasetRevisionOutputQueryLayoutPatchResponses];

export type GetMapOutputOutputMapMapIdOutputTypeGetData = {
    body?: never;
    path: {
        /**
         * Mapid
         */
        mapId: string;
        output_type: TerranovaOutputType;
    };
    query?: {
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | number;
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/output/map/{mapId}/{output_type}/';
};

export type GetMapOutputOutputMapMapIdOutputTypeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMapOutputOutputMapMapIdOutputTypeGetError = GetMapOutputOutputMapMapIdOutputTypeGetErrors[keyof GetMapOutputOutputMapMapIdOutputTypeGetErrors];

export type GetMapOutputOutputMapMapIdOutputTypeGetResponses = {
    /**
     * Successful Response
     */
    200: _Map;
};

export type GetMapOutputOutputMapMapIdOutputTypeGetResponse = GetMapOutputOutputMapMapIdOutputTypeGetResponses[keyof GetMapOutputOutputMapMapIdOutputTypeGetResponses];

export type OutputPublicMapPublicOutputMapMapIdGetData = {
    body?: never;
    path: {
        /**
         * Mapid
         */
        mapId: string;
    };
    query?: {
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | number;
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/public/output/map/{mapId}/';
};

export type OutputPublicMapPublicOutputMapMapIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutputPublicMapPublicOutputMapMapIdGetError = OutputPublicMapPublicOutputMapMapIdGetErrors[keyof OutputPublicMapPublicOutputMapMapIdGetErrors];

export type OutputPublicMapPublicOutputMapMapIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OutputTypedPublicMapPublicOutputMapMapIdOutputTypeGetData = {
    body?: never;
    path: {
        /**
         * Mapid
         */
        mapId: string;
        output_type: TerranovaOutputType;
    };
    query?: {
        /**
         * Version
         *
         * <i>Available values</i> : 'all' for all versions, 'latest' for latest, or an integer for a specific version
         */
        version?: VersionEnum | number;
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/public/output/map/{mapId}/{output_type}/';
};

export type OutputTypedPublicMapPublicOutputMapMapIdOutputTypeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutputTypedPublicMapPublicOutputMapMapIdOutputTypeGetError = OutputTypedPublicMapPublicOutputMapMapIdOutputTypeGetErrors[keyof OutputTypedPublicMapPublicOutputMapMapIdOutputTypeGetErrors];

export type OutputTypedPublicMapPublicOutputMapMapIdOutputTypeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OutputMapPatchOutputMapPatchData = {
    body: MapRevision;
    path?: never;
    query?: never;
    url: '/output/map/';
};

export type OutputMapPatchOutputMapPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutputMapPatchOutputMapPatchError = OutputMapPatchOutputMapPatchErrors[keyof OutputMapPatchOutputMapPatchErrors];

export type OutputMapPatchOutputMapPatchResponses = {
    /**
     * Successful Response
     */
    200: MapRevision;
};

export type OutputMapPatchOutputMapPatchResponse = OutputMapPatchOutputMapPatchResponses[keyof OutputMapPatchOutputMapPatchResponses];

export type GetUserdataUserdataGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/userdata/';
};

export type GetUserdataUserdataGetResponses = {
    /**
     * Successful Response
     */
    200: UserData;
};

export type GetUserdataUserdataGetResponse = GetUserdataUserdataGetResponses[keyof GetUserdataUserdataGetResponses];

export type CreateUserdataUserdataPostData = {
    body: UserDataRevision;
    path?: never;
    query?: never;
    url: '/userdata/';
};

export type CreateUserdataUserdataPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserdataUserdataPostError = CreateUserdataUserdataPostErrors[keyof CreateUserdataUserdataPostErrors];

export type CreateUserdataUserdataPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateUserdataUserdataPutData = {
    body: UserDataRevision;
    path?: never;
    query?: never;
    url: '/userdata/';
};

export type UpdateUserdataUserdataPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserdataUserdataPutError = UpdateUserdataUserdataPutErrors[keyof UpdateUserdataUserdataPutErrors];

export type UpdateUserdataUserdataPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DistinctValuesSheetsSheetIdDistinctColumnGetData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: string;
        /**
         * Column
         */
        column: string;
    };
    query?: {
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/sheets/{sheet_id}/distinct/{column}/';
};

export type DistinctValuesSheetsSheetIdDistinctColumnGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DistinctValuesSheetsSheetIdDistinctColumnGetError = DistinctValuesSheetsSheetIdDistinctColumnGetErrors[keyof DistinctValuesSheetsSheetIdDistinctColumnGetErrors];

export type DistinctValuesSheetsSheetIdDistinctColumnGetResponses = {
    /**
     * Response Distinct Values Sheets  Sheet Id  Distinct  Column   Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type DistinctValuesSheetsSheetIdDistinctColumnGetResponse = DistinctValuesSheetsSheetIdDistinctColumnGetResponses[keyof DistinctValuesSheetsSheetIdDistinctColumnGetResponses];

export type EdgesSheetsSheetIdEdgesGetData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Id
         */
        id?: Array<string>;
        /**
         * Id Not Like
         */
        id_not_like?: Array<string>;
        /**
         * Id Like
         */
        id_like?: Array<string>;
        /**
         * Id Not Equal
         */
        id_not_equal?: Array<string>;
        /**
         * Id Equal
         */
        id_equal?: Array<string>;
        /**
         * Name
         */
        name?: Array<string>;
        /**
         * Name Not Like
         */
        name_not_like?: Array<string>;
        /**
         * Name Like
         */
        name_like?: Array<string>;
        /**
         * Name Not Equal
         */
        name_not_equal?: Array<string>;
        /**
         * Name Equal
         */
        name_equal?: Array<string>;
        /**
         * Description
         */
        description?: Array<string>;
        /**
         * Description Not Like
         */
        description_not_like?: Array<string>;
        /**
         * Description Like
         */
        description_like?: Array<string>;
        /**
         * Description Not Equal
         */
        description_not_equal?: Array<string>;
        /**
         * Description Equal
         */
        description_equal?: Array<string>;
        /**
         * Endpoints Name
         */
        endpoints_name?: Array<string>;
        /**
         * Endpoints Name Not Like
         */
        endpoints_name_not_like?: Array<string>;
        /**
         * Endpoints Name Like
         */
        endpoints_name_like?: Array<string>;
        /**
         * Endpoints Name Not Equal
         */
        endpoints_name_not_equal?: Array<string>;
        /**
         * Endpoints Name Equal
         */
        endpoints_name_equal?: Array<string>;
        /**
         * Endpoints Description
         */
        endpoints_description?: Array<string>;
        /**
         * Endpoints Description Not Like
         */
        endpoints_description_not_like?: Array<string>;
        /**
         * Endpoints Description Like
         */
        endpoints_description_like?: Array<string>;
        /**
         * Endpoints Description Not Equal
         */
        endpoints_description_not_equal?: Array<string>;
        /**
         * Endpoints Description Equal
         */
        endpoints_description_equal?: Array<string>;
        /**
         * Source
         */
        source?: Array<string>;
        /**
         * Source Not Like
         */
        source_not_like?: Array<string>;
        /**
         * Source Like
         */
        source_like?: Array<string>;
        /**
         * Source Not Equal
         */
        source_not_equal?: Array<string>;
        /**
         * Source Equal
         */
        source_equal?: Array<string>;
        /**
         * Destination
         */
        destination?: Array<string>;
        /**
         * Destination Not Like
         */
        destination_not_like?: Array<string>;
        /**
         * Destination Like
         */
        destination_like?: Array<string>;
        /**
         * Destination Not Equal
         */
        destination_not_equal?: Array<string>;
        /**
         * Destination Equal
         */
        destination_equal?: Array<string>;
    };
    url: '/sheets/{sheet_id}/edges/';
};

export type EdgesSheetsSheetIdEdgesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EdgesSheetsSheetIdEdgesGetError = EdgesSheetsSheetIdEdgesGetErrors[keyof EdgesSheetsSheetIdEdgesGetErrors];

export type EdgesSheetsSheetIdEdgesGetResponses = {
    /**
     * Response Edges Sheets  Sheet Id  Edges  Get
     *
     * Successful Response
     */
    200: Array<Edge>;
};

export type EdgesSheetsSheetIdEdgesGetResponse = EdgesSheetsSheetIdEdgesGetResponses[keyof EdgesSheetsSheetIdEdgesGetResponses];

export type ListStaticCredentialsSheetsCredentialsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sheets/credentials/';
};

export type ListStaticCredentialsSheetsCredentialsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListSheetsSheetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/sheets/';
};

export type ListSheetsSheetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSheetsSheetsGetError = ListSheetsSheetsGetErrors[keyof ListSheetsSheetsGetErrors];

export type ListSheetsSheetsGetResponses = {
    /**
     * Response List Sheets Sheets  Get
     *
     * Successful Response
     */
    200: Array<GoogleSheet>;
};

export type ListSheetsSheetsGetResponse = ListSheetsSheetsGetResponses[keyof ListSheetsSheetsGetResponses];

export type ListFilterableColumnsSheetsSheetIdFilterableColumnsGetData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: string;
    };
    query?: never;
    url: '/sheets/{sheet_id}/filterable_columns/';
};

export type ListFilterableColumnsSheetsSheetIdFilterableColumnsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFilterableColumnsSheetsSheetIdFilterableColumnsGetError = ListFilterableColumnsSheetsSheetIdFilterableColumnsGetErrors[keyof ListFilterableColumnsSheetsSheetIdFilterableColumnsGetErrors];

export type ListFilterableColumnsSheetsSheetIdFilterableColumnsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersUserGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: unknown;
    };
    url: '/user/';
};

export type ListUsersUserGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersUserGetError = ListUsersUserGetErrors[keyof ListUsersUserGetErrors];

export type ListUsersUserGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CurrentUserCurrentUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/current_user/';
};

export type CurrentUserCurrentUserGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateUserUserPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/user';
};

export type CreateUserUserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUserPostError = CreateUserUserPostErrors[keyof CreateUserUserPostErrors];

export type CreateUserUserPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteUserUserUsernameDeleteData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/user/{username}/';
};

export type DeleteUserUserUsernameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUserUsernameDeleteError = DeleteUserUserUsernameDeleteErrors[keyof DeleteUserUserUsernameDeleteErrors];

export type DeleteUserUserUsernameDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateUserUserUsernamePutData = {
    body: UserUpdate;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/user/{username}/';
};

export type UpdateUserUserUsernamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUserUsernamePutError = UpdateUserUserUsernamePutErrors[keyof UpdateUserUserUsernamePutErrors];

export type UpdateUserUserUsernamePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SetPasswordUserUsernameSetPasswordPutData = {
    body: PasswordReset;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/user/{username}/set_password/';
};

export type SetPasswordUserUsernameSetPasswordPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetPasswordUserUsernameSetPasswordPutError = SetPasswordUserUsernameSetPasswordPutErrors[keyof SetPasswordUserUsernameSetPasswordPutErrors];

export type SetPasswordUserUsernameSetPasswordPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EndpointsListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type EndpointsListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
